// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebQLHS.Models;

#nullable disable

namespace WebQLHS.Migrations
{
    [DbContext(typeof(QLHS_1Context))]
    partial class QLHS_1ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebQLHS.Models.BaiTap", b =>
                {
                    b.Property<string>("MaBaiTap")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("char(15)")
                        .IsFixedLength();

                    b.Property<string>("MaLopHoc")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("char(15)")
                        .IsFixedLength();

                    b.Property<string>("MaNv")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("char(15)")
                        .HasColumnName("MaNV")
                        .IsFixedLength();

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("date");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("date");

                    b.HasKey("MaBaiTap")
                        .HasName("PK__BaiTap__3AF6A91584D8C7EE");

                    b.HasIndex("MaLopHoc");

                    b.HasIndex("MaNv");

                    b.ToTable("BaiTap", (string)null);
                });

            modelBuilder.Entity("WebQLHS.Models.BangDiem", b =>
                {
                    b.Property<string>("MaBangDiem")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("char(15)")
                        .IsFixedLength();

                    b.Property<string>("MaHs")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("char(15)")
                        .HasColumnName("MaHS")
                        .IsFixedLength();

                    b.Property<string>("MaMh")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("char(15)")
                        .HasColumnName("MaMH")
                        .IsFixedLength();

                    b.HasKey("MaBangDiem")
                        .HasName("PK__BangDiem__9D44FE48327549F4");

                    b.HasIndex("MaMh");

                    b.HasIndex(new[] { "MaHs", "MaMh" }, "UQ__BangDiem__A557FB139EF3E120")
                        .IsUnique();

                    b.ToTable("BangDiem", (string)null);
                });

            modelBuilder.Entity("WebQLHS.Models.ChucVu", b =>
                {
                    b.Property<string>("MaCv")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("char(15)")
                        .HasColumnName("MaCV")
                        .IsFixedLength();

                    b.Property<string>("MaNv")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("char(15)")
                        .HasColumnName("MaNV")
                        .IsFixedLength();

                    b.Property<string>("TenChucVu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaCv")
                        .HasName("PK__ChucVu__27258E768B459AE8");

                    b.HasIndex("MaNv");

                    b.ToTable("ChucVu", (string)null);
                });

            modelBuilder.Entity("WebQLHS.Models.HocSinh", b =>
                {
                    b.Property<string>("MaHs")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("char(15)")
                        .HasColumnName("MaHS")
                        .IsFixedLength();

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EmailHocSinh")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaLopHoc")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("char(15)")
                        .IsFixedLength();

                    b.Property<string>("MaTk")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("char(15)")
                        .HasColumnName("MaTK")
                        .IsFixedLength();

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("date");

                    b.HasKey("MaHs")
                        .HasName("PK__HocSinh__2725A6EF79DE009C");

                    b.HasIndex("MaLopHoc");

                    b.HasIndex("MaTk");

                    b.ToTable("HocSinh", (string)null);
                });

            modelBuilder.Entity("WebQLHS.Models.Lop", b =>
                {
                    b.Property<string>("MaLopHoc")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("char(15)")
                        .IsFixedLength();

                    b.Property<int>("SiSo")
                        .HasColumnType("int");

                    b.Property<string>("TenLop")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaLopHoc")
                        .HasName("PK__Lop__FEE0578410A94583");

                    b.ToTable("Lop", (string)null);
                });

            modelBuilder.Entity("WebQLHS.Models.MonHoc", b =>
                {
                    b.Property<string>("MaMh")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("char(15)")
                        .HasColumnName("MaMH")
                        .IsFixedLength();

                    b.Property<string>("TenMonHoc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaMh")
                        .HasName("PK__MonHoc__2725DFD979F42C5F");

                    b.ToTable("MonHoc", (string)null);
                });

            modelBuilder.Entity("WebQLHS.Models.MonHocTkb", b =>
                {
                    b.Property<string>("MaMhTkb")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("char(15)")
                        .HasColumnName("MaMH_TKB")
                        .IsFixedLength();

                    b.Property<string>("MaMh")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("char(15)")
                        .HasColumnName("MaMH")
                        .IsFixedLength();

                    b.Property<string>("MaTkb")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("char(15)")
                        .HasColumnName("MaTKB")
                        .IsFixedLength();

                    b.HasKey("MaMhTkb")
                        .HasName("PK__MonHoc_T__8A44B1D6D7BB5549");

                    b.HasIndex("MaTkb");

                    b.HasIndex(new[] { "MaMh", "MaTkb" }, "UQ__MonHoc_T__D43142B80427D49C")
                        .IsUnique();

                    b.ToTable("MonHoc_TKB", (string)null);
                });

            modelBuilder.Entity("WebQLHS.Models.NhanVien", b =>
                {
                    b.Property<string>("MaNv")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("char(15)")
                        .HasColumnName("MaNV")
                        .IsFixedLength();

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaLopHoc")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("char(15)")
                        .IsFixedLength();

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("date");

                    b.HasKey("MaNv")
                        .HasName("PK__NhanVien__2725D70A38314326");

                    b.HasIndex("MaLopHoc");

                    b.ToTable("NhanVien", (string)null);
                });

            modelBuilder.Entity("WebQLHS.Models.NhapDiem", b =>
                {
                    b.Property<string>("MaNhapDiem")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("char(15)")
                        .IsFixedLength();

                    b.Property<double>("DiemSo")
                        .HasColumnType("float");

                    b.Property<string>("MaBangDiem")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("char(15)")
                        .IsFixedLength();

                    b.Property<string>("MaMh")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("char(15)")
                        .HasColumnName("MaMH")
                        .IsFixedLength();

                    b.Property<string>("MaNv")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("char(15)")
                        .HasColumnName("MaNV")
                        .IsFixedLength();

                    b.HasKey("MaNhapDiem")
                        .HasName("PK__NhapDiem__FCC9F48B3AC1B78A");

                    b.HasIndex("MaBangDiem");

                    b.HasIndex("MaNv");

                    b.HasIndex(new[] { "MaMh", "MaNv" }, "UQ__NhapDiem__955782A8EE35622A")
                        .IsUnique();

                    b.ToTable("NhapDiem", (string)null);
                });

            modelBuilder.Entity("WebQLHS.Models.TaiKhoan", b =>
                {
                    b.Property<string>("MaTk")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("char(15)")
                        .HasColumnName("MaTK")
                        .IsFixedLength();

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("LoaiTaiKhoan")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaNv")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("char(15)")
                        .HasColumnName("MaNV")
                        .IsFixedLength();

                    b.Property<string>("Mk")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("MK");

                    b.HasKey("MaTk")
                        .HasName("PK__TaiKhoan__27250070B2D309CD");

                    b.HasIndex("MaNv");

                    b.ToTable("TaiKhoan", (string)null);
                });

            modelBuilder.Entity("WebQLHS.Models.ThuChi", b =>
                {
                    b.Property<string>("MaGiaoDich")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("char(15)")
                        .IsFixedLength();

                    b.Property<string>("LoaiGiaoDich")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaHs")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("char(15)")
                        .HasColumnName("MaHS")
                        .IsFixedLength();

                    b.Property<string>("MaNv")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("char(15)")
                        .HasColumnName("MaNV")
                        .IsFixedLength();

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("NgayGiaoDich")
                        .HasColumnType("date");

                    b.Property<double>("SoTien")
                        .HasColumnType("float");

                    b.HasKey("MaGiaoDich")
                        .HasName("PK__ThuChi__0A2A24EB12D1440D");

                    b.HasIndex("MaHs");

                    b.HasIndex("MaNv");

                    b.ToTable("ThuChi", (string)null);
                });

            modelBuilder.Entity("WebQLHS.Models.Tkb", b =>
                {
                    b.Property<string>("MaTkb")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("char(15)")
                        .HasColumnName("MaTKB")
                        .IsFixedLength();

                    b.Property<string>("MaHs")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("char(15)")
                        .HasColumnName("MaHS")
                        .IsFixedLength();

                    b.Property<string>("MaNv")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("char(15)")
                        .HasColumnName("MaNV")
                        .IsFixedLength();

                    b.Property<string>("Thu")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Tiet")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaTkb")
                        .HasName("PK__TKB__3149D60EC16D6E7C");

                    b.HasIndex("MaHs");

                    b.HasIndex("MaNv");

                    b.ToTable("TKB", (string)null);
                });

            modelBuilder.Entity("WebQLHS.Models.BaiTap", b =>
                {
                    b.HasOne("WebQLHS.Models.Lop", "MaLopHocNavigation")
                        .WithMany("BaiTaps")
                        .HasForeignKey("MaLopHoc")
                        .IsRequired()
                        .HasConstraintName("FK__BaiTap__MaLopHoc__3F466844");

                    b.HasOne("WebQLHS.Models.NhanVien", "MaNvNavigation")
                        .WithMany("BaiTaps")
                        .HasForeignKey("MaNv")
                        .IsRequired()
                        .HasConstraintName("FK__BaiTap__MaNV__3E52440B");

                    b.Navigation("MaLopHocNavigation");

                    b.Navigation("MaNvNavigation");
                });

            modelBuilder.Entity("WebQLHS.Models.BangDiem", b =>
                {
                    b.HasOne("WebQLHS.Models.HocSinh", "MaHsNavigation")
                        .WithMany("BangDiems")
                        .HasForeignKey("MaHs")
                        .IsRequired()
                        .HasConstraintName("FK__BangDiem__MaHS__59063A47");

                    b.HasOne("WebQLHS.Models.MonHoc", "MaMhNavigation")
                        .WithMany("BangDiems")
                        .HasForeignKey("MaMh")
                        .IsRequired()
                        .HasConstraintName("FK__BangDiem__MaMH__59FA5E80");

                    b.Navigation("MaHsNavigation");

                    b.Navigation("MaMhNavigation");
                });

            modelBuilder.Entity("WebQLHS.Models.ChucVu", b =>
                {
                    b.HasOne("WebQLHS.Models.NhanVien", "MaNvNavigation")
                        .WithMany("ChucVus")
                        .HasForeignKey("MaNv")
                        .IsRequired()
                        .HasConstraintName("FK__ChucVu__MaNV__4222D4EF");

                    b.Navigation("MaNvNavigation");
                });

            modelBuilder.Entity("WebQLHS.Models.HocSinh", b =>
                {
                    b.HasOne("WebQLHS.Models.Lop", "MaLopHocNavigation")
                        .WithMany("HocSinhs")
                        .HasForeignKey("MaLopHoc")
                        .IsRequired()
                        .HasConstraintName("FK__HocSinh__MaLopHo__47DBAE45");

                    b.HasOne("WebQLHS.Models.TaiKhoan", "MaTkNavigation")
                        .WithMany("HocSinhs")
                        .HasForeignKey("MaTk")
                        .IsRequired()
                        .HasConstraintName("FK__HocSinh__MaTK__48CFD27E");

                    b.Navigation("MaLopHocNavigation");

                    b.Navigation("MaTkNavigation");
                });

            modelBuilder.Entity("WebQLHS.Models.MonHocTkb", b =>
                {
                    b.HasOne("WebQLHS.Models.MonHoc", "MaMhNavigation")
                        .WithMany("MonHocTkbs")
                        .HasForeignKey("MaMh")
                        .IsRequired()
                        .HasConstraintName("FK__MonHoc_TKB__MaMH__5441852A");

                    b.HasOne("WebQLHS.Models.Tkb", "MaTkbNavigation")
                        .WithMany("MonHocTkbs")
                        .HasForeignKey("MaTkb")
                        .IsRequired()
                        .HasConstraintName("FK__MonHoc_TK__MaTKB__5535A963");

                    b.Navigation("MaMhNavigation");

                    b.Navigation("MaTkbNavigation");
                });

            modelBuilder.Entity("WebQLHS.Models.NhanVien", b =>
                {
                    b.HasOne("WebQLHS.Models.Lop", "MaLopHocNavigation")
                        .WithMany("NhanViens")
                        .HasForeignKey("MaLopHoc")
                        .IsRequired()
                        .HasConstraintName("FK__NhanVien__MaLopH__3B75D760");

                    b.Navigation("MaLopHocNavigation");
                });

            modelBuilder.Entity("WebQLHS.Models.NhapDiem", b =>
                {
                    b.HasOne("WebQLHS.Models.BangDiem", "MaBangDiemNavigation")
                        .WithMany("NhapDiems")
                        .HasForeignKey("MaBangDiem")
                        .IsRequired()
                        .HasConstraintName("FK__NhapDiem__MaBang__5FB337D6");

                    b.HasOne("WebQLHS.Models.MonHoc", "MaMhNavigation")
                        .WithMany("NhapDiems")
                        .HasForeignKey("MaMh")
                        .IsRequired()
                        .HasConstraintName("FK__NhapDiem__MaMH__5DCAEF64");

                    b.HasOne("WebQLHS.Models.NhanVien", "MaNvNavigation")
                        .WithMany("NhapDiems")
                        .HasForeignKey("MaNv")
                        .IsRequired()
                        .HasConstraintName("FK__NhapDiem__MaNV__5EBF139D");

                    b.Navigation("MaBangDiemNavigation");

                    b.Navigation("MaMhNavigation");

                    b.Navigation("MaNvNavigation");
                });

            modelBuilder.Entity("WebQLHS.Models.TaiKhoan", b =>
                {
                    b.HasOne("WebQLHS.Models.NhanVien", "MaNvNavigation")
                        .WithMany("TaiKhoans")
                        .HasForeignKey("MaNv")
                        .IsRequired()
                        .HasConstraintName("FK__TaiKhoan__MaNV__44FF419A");

                    b.Navigation("MaNvNavigation");
                });

            modelBuilder.Entity("WebQLHS.Models.ThuChi", b =>
                {
                    b.HasOne("WebQLHS.Models.HocSinh", "MaHsNavigation")
                        .WithMany("ThuChis")
                        .HasForeignKey("MaHs")
                        .IsRequired()
                        .HasConstraintName("FK__ThuChi__MaHS__4F7CD00D");

                    b.HasOne("WebQLHS.Models.NhanVien", "MaNvNavigation")
                        .WithMany("ThuChis")
                        .HasForeignKey("MaNv")
                        .IsRequired()
                        .HasConstraintName("FK__ThuChi__MaNV__5070F446");

                    b.Navigation("MaHsNavigation");

                    b.Navigation("MaNvNavigation");
                });

            modelBuilder.Entity("WebQLHS.Models.Tkb", b =>
                {
                    b.HasOne("WebQLHS.Models.HocSinh", "MaHsNavigation")
                        .WithMany("Tkbs")
                        .HasForeignKey("MaHs")
                        .IsRequired()
                        .HasConstraintName("FK__TKB__MaHS__4BAC3F29");

                    b.HasOne("WebQLHS.Models.NhanVien", "MaNvNavigation")
                        .WithMany("Tkbs")
                        .HasForeignKey("MaNv")
                        .IsRequired()
                        .HasConstraintName("FK__TKB__MaNV__4CA06362");

                    b.Navigation("MaHsNavigation");

                    b.Navigation("MaNvNavigation");
                });

            modelBuilder.Entity("WebQLHS.Models.BangDiem", b =>
                {
                    b.Navigation("NhapDiems");
                });

            modelBuilder.Entity("WebQLHS.Models.HocSinh", b =>
                {
                    b.Navigation("BangDiems");

                    b.Navigation("ThuChis");

                    b.Navigation("Tkbs");
                });

            modelBuilder.Entity("WebQLHS.Models.Lop", b =>
                {
                    b.Navigation("BaiTaps");

                    b.Navigation("HocSinhs");

                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("WebQLHS.Models.MonHoc", b =>
                {
                    b.Navigation("BangDiems");

                    b.Navigation("MonHocTkbs");

                    b.Navigation("NhapDiems");
                });

            modelBuilder.Entity("WebQLHS.Models.NhanVien", b =>
                {
                    b.Navigation("BaiTaps");

                    b.Navigation("ChucVus");

                    b.Navigation("NhapDiems");

                    b.Navigation("TaiKhoans");

                    b.Navigation("ThuChis");

                    b.Navigation("Tkbs");
                });

            modelBuilder.Entity("WebQLHS.Models.TaiKhoan", b =>
                {
                    b.Navigation("HocSinhs");
                });

            modelBuilder.Entity("WebQLHS.Models.Tkb", b =>
                {
                    b.Navigation("MonHocTkbs");
                });
#pragma warning restore 612, 618
        }
    }
}
